x-airflow-common: &airflow-common
  build:
    context: ..
    dockerfile: airflow/Dockerfile
  env_file:
    - ./.env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./data:/opt/airflow/data
    - ../feed_package/rss_feed_package:/opt/airflow/rss_feed_package
  networks:
    - airflow-network

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    restart: always

  redis:
    image: redis:latest
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 50
    restart: always

  airflow-webserver:
    <<: *airflow-common
    hostname: airflow-webserver
    ports:
      - "8080:8080"
    environment:
      - _AIRFLOW_DB_MIGRATE=true
      - _AIRFLOW_WWW_USER_CREATE=true
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - _AIRFLOW_WWW_USER_FIRSTNAME=admin
      - _AIRFLOW_WWW_USER_LASTNAME=user
      - _AIRFLOW_WWW_USER_EMAIL=admin@example.com
      - _AIRFLOW_WWW_USER_ROLE=Admin
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=http://airflow-webserver:8793
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
    command: airflow webserver
    depends_on:
      - postgres
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    hostname: airflow-scheduler
    environment:
      - _AIRFLOW_DB_MIGRATE=true
      - AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER=http://airflow-webserver:8793
      - AIRFLOW__LOGGING__REMOTE_LOGGING=True
    command: airflow scheduler
    depends_on:
      - airflow-webserver
    restart: always

volumes:
  postgres-db-volume:
  redis_data:

networks:
  airflow-network:
    driver: bridge 